[package]
name = "vector_search"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.204"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.92"
console_error_panic_hook = "0.1.7"

[lib]
crate-type = ["cdylib", "rlib"]
